name = "website"
type = "javascript"

account_id = "5d1e8733fafc56dc67c31661af212d57"
workers_dev = true
compatibility_date = "2024-08-06"

[site]
bucket = "./dist"
entry-point = "."

[build]
command = "npm run build"
